Public Class LISTADO_DE_NOTAS_DE_INTRODUCCION_A_LOS_AMBIENTES_VIRTUALES_003
    Private Sub btnLISTANOTASINTRODUCCIONALOSAMBIENTESVIRTUALES003_Click(sender As Object, e As EventArgs) Handles btnLISTANOTASINTRODUCCIONALOSAMBIENTESVIRTUALES003.Click
        Me.Close()
        NOTAS_EN_CURSOS.Show()
    End Sub
End Class