Public Class LISTADO_DE_NOTAS_DE_COMUNICACION_ORAL_Y_ESCRITA_001
    Private Sub btnSALIRLISTANOTASCOMUNICACIONORALYESCRITA001_Click(sender As Object, e As EventArgs) Handles btnSALIRLISTANOTASCOMUNICACIONORALYESCRITA001.Click
        Me.Close()
        NOTAS_EN_CURSOS.Show()
    End Sub
End Class